[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
# solce_version = "0.8.17"
# solce_version = ["0.8.13", "0.7.6"]
auto_detect_solc = true
# via_ir = true
# optimizer = true


# auto_detect_solc = true
